/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.entities.Autor;
import model.entities.Biblioteca;
import model.entities.Categoria;
import model.entities.Editora;
import model.entities.Emprestimo;
import model.entities.Livro;
import model.entities.PedidoEmprestimo;
import model.entities.Usuario;

/**
 *
 * @author kassi
 */
public class MainView extends javax.swing.JFrame {
    private static Biblioteca biblioteca = new Biblioteca();
    private static PedidoEmprestimo pedidoEmprestimo = null;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        listUsers();
        labelNomeLivro.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserModal = new javax.swing.JDialog();
        txtCpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        tbOptions = new javax.swing.JPopupMenu();
        menuEditUser = new javax.swing.JMenuItem();
        menuDeleteUser = new javax.swing.JMenuItem();
        popupBook = new javax.swing.JPopupMenu();
        addAoPedido = new javax.swing.JMenuItem();
        modalSolicitarCpf = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        txtNovoEmprestimoModalCpf = new javax.swing.JTextField();
        btnConfirmarCpf = new javax.swing.JButton();
        btnCancelarCpf = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        booksPanel = new javax.swing.JPanel();
        txtBookSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBookSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBookIsbn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBookYear = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtBookAuthor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBookEditora = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBookCategoria = new javax.swing.JTextField();
        btnBookRegister = new javax.swing.JButton();
        btnBookUpdate = new javax.swing.JButton();
        btnBookClearFields = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBooks = new javax.swing.JTable();
        btnNovoEmprestimo = new javax.swing.JButton();
        painelPedido = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtCpfPedidoEmprestimo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPedidoEmprestimo = new javax.swing.JTable();
        btnSavePedidoEmp = new javax.swing.JButton();
        painelStatusLivro = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        labelNomeLivro = new javax.swing.JLabel();
        labelBookStatus = new javax.swing.JLabel();
        btnAdicionarAoPedido = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        newUserBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsers = new javax.swing.JTable();

        newUserModal.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        newUserModal.setTitle("Cadastrar usuário");
        newUserModal.setAlwaysOnTop(true);
        newUserModal.setLocation(new java.awt.Point(0, 0));
        newUserModal.setModal(true);
        newUserModal.setSize(new java.awt.Dimension(327, 500));
        newUserModal.setType(java.awt.Window.Type.POPUP);

        jLabel2.setText("Cpf");

        jLabel3.setText("Nome");

        jLabel4.setText("Email");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone");

        jLabel6.setText("Data de nascimento");

        jLabel7.setText("Endereço");

        registerBtn.setBackground(new java.awt.Color(102, 204, 0));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Cadastrar");
        registerBtn.setBorder(null);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 102, 102));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelBtn.setText("Cancelar");
        cancelBtn.setBorder(null);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        cancelBtn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cancelBtnPropertyChange(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(102, 204, 0));
        editBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Salvar");
        editBtn.setBorder(null);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUserModalLayout = new javax.swing.GroupLayout(newUserModal.getContentPane());
        newUserModal.getContentPane().setLayout(newUserModalLayout);
        newUserModalLayout.setHorizontalGroup(
            newUserModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserModalLayout.createSequentialGroup()
                .addGroup(newUserModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserModalLayout.createSequentialGroup()
                        .addContainerGap(136, Short.MAX_VALUE)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newUserModalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(newUserModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(txtCpf)
                            .addComponent(txtNome)
                            .addComponent(txtEmail)
                            .addComponent(txtTelefone)
                            .addComponent(txtNascimento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newUserModalLayout.setVerticalGroup(
            newUserModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserModalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(newUserModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        menuEditUser.setText("editar");
        menuEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditUserActionPerformed(evt);
            }
        });
        tbOptions.add(menuEditUser);

        menuDeleteUser.setText("Deletar");
        menuDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteUserActionPerformed(evt);
            }
        });
        tbOptions.add(menuDeleteUser);

        addAoPedido.setText("jMenuItem1");
        addAoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAoPedidoActionPerformed(evt);
            }
        });
        popupBook.add(addAoPedido);

        modalSolicitarCpf.setMinimumSize(new java.awt.Dimension(364, 160));
        modalSolicitarCpf.setModal(true);

        jLabel16.setText("CPF");

        btnConfirmarCpf.setText("Confirmar");
        btnConfirmarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCpfActionPerformed(evt);
            }
        });

        btnCancelarCpf.setText("Cancelar");
        btnCancelarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modalSolicitarCpfLayout = new javax.swing.GroupLayout(modalSolicitarCpf.getContentPane());
        modalSolicitarCpf.getContentPane().setLayout(modalSolicitarCpfLayout);
        modalSolicitarCpfLayout.setHorizontalGroup(
            modalSolicitarCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalSolicitarCpfLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNovoEmprestimoModalCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modalSolicitarCpfLayout.createSequentialGroup()
                .addGap(139, 181, Short.MAX_VALUE)
                .addComponent(btnCancelarCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarCpf)
                .addGap(17, 17, 17))
            .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalSolicitarCpfLayout.setVerticalGroup(
            modalSolicitarCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalSolicitarCpfLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(modalSolicitarCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovoEmprestimoModalCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(modalSolicitarCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarCpf)
                    .addComponent(btnCancelarCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel8.setText("Pesquisar livro");

        btnBookSearch.setText("Buscar");
        btnBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookSearchActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        jLabel9.setText("Título");

        jLabel10.setText("Id");

        txtBookId.setEnabled(false);

        jLabel11.setText("Isbn");

        jLabel12.setText("Publicado em");

        jLabel13.setText("Autor(es)");

        jLabel14.setText("Editora");

        jLabel15.setText("Categoria");

        btnBookRegister.setText("Cadastrar");
        btnBookRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookRegisterActionPerformed(evt);
            }
        });

        btnBookUpdate.setText("Salvar");
        btnBookUpdate.setVisible(false);

        btnBookClearFields.setText("Limpar");
        btnBookClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookClearFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBookTitle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookIsbn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookYear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookEditora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBookClearFields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookRegister)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtBookYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBookEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtBookCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookRegister)
                    .addComponent(btnBookUpdate)
                    .addComponent(btnBookClearFields))
                .addGap(29, 29, 29))
        );

        tbBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Isbn", "Autor(es)", "Publicado em", "Categoria", "Editora"
            }
        ));
        tbBooks.setComponentPopupMenu(popupBook);
        tbBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbBooks.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbBooks);
        tbBooks.getSelectionModel().addListSelectionListener(listListener);

        btnNovoEmprestimo.setText("Novo Empréstimo");
        btnNovoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoEmprestimoActionPerformed(evt);
            }
        });

        painelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido de empréstimo"));

        jLabel17.setText("Cpf");

        txtCpfPedidoEmprestimo.setEnabled(false);

        tbPedidoEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Título"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPedidoEmprestimo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPedidoEmprestimo.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbPedidoEmprestimo);
        if (tbPedidoEmprestimo.getColumnModel().getColumnCount() > 0) {
            tbPedidoEmprestimo.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnSavePedidoEmp.setText("Enviar");
        btnSavePedidoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePedidoEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPedidoLayout = new javax.swing.GroupLayout(painelPedido);
        painelPedido.setLayout(painelPedidoLayout);
        painelPedidoLayout.setHorizontalGroup(
            painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPedidoLayout.createSequentialGroup()
                .addGroup(painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSavePedidoEmp)
                    .addGroup(painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelPedidoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCpfPedidoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelPedidoLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        painelPedidoLayout.setVerticalGroup(
            painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfPedidoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnSavePedidoEmp)
                .addContainerGap())
        );

        jLabel18.setText("Status");

        labelNomeLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAdicionarAoPedido.setText("Adicionar ao pedido");
        btnAdicionarAoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAoPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelStatusLivroLayout = new javax.swing.GroupLayout(painelStatusLivro);
        painelStatusLivro.setLayout(painelStatusLivroLayout);
        painelStatusLivroLayout.setHorizontalGroup(
            painelStatusLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelStatusLivroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelStatusLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelStatusLivroLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelStatusLivroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionarAoPedido)
                .addGap(25, 25, 25))
        );
        painelStatusLivroLayout.setVerticalGroup(
            painelStatusLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelStatusLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelStatusLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelBookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAdicionarAoPedido)
                .addGap(16, 16, 16))
        );

        btnAdicionarAoPedido.setVisible(false);

        painelStatusLivro.setVisible(false);

        javax.swing.GroupLayout booksPanelLayout = new javax.swing.GroupLayout(booksPanel);
        booksPanel.setLayout(booksPanelLayout);
        booksPanelLayout.setHorizontalGroup(
            booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(booksPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnNovoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(booksPanelLayout.createSequentialGroup()
                        .addComponent(txtBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBookSearch))
                    .addComponent(jScrollPane2)
                    .addComponent(painelStatusLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        booksPanelLayout.setVerticalGroup(
            booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booksPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(booksPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBookSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(booksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelStatusLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        painelPedido.setVisible(false);

        jTabbedPane1.addTab("Biblioteca", booksPanel);

        jLabel1.setText("Cpf / nome");

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        newUserBtn.setText("Novo usuário");
        newUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnActionPerformed(evt);
            }
        });

        tbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cpf", "Nome", "Email", "Telefone", "Data nascimento", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsers.setComponentPopupMenu(tbOptions);
        tbUsers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbUsers);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newUserBtn)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearch))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newUserBtn)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuários", userPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        registerBtn.setVisible(true);
        editBtn.setVisible(false);
        newUserModal.setVisible(true);
    }//GEN-LAST:event_newUserBtnActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void cancelBtnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cancelBtnPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnPropertyChange

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        registerUser();
        clearFields(txtCpf, txtEmail, txtEndereco, txtNome, txtNascimento, txtTelefone);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        newUserModal.dispose();
        clearFields(txtCpf, txtEmail, txtEndereco, txtNome, txtNascimento, txtTelefone);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        editUser();
    }//GEN-LAST:event_editBtnActionPerformed

    private void menuEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditUserActionPerformed
        showEditModal();    
    }//GEN-LAST:event_menuEditUserActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchUser();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void menuDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteUserActionPerformed
        deleteUser();
    }//GEN-LAST:event_menuDeleteUserActionPerformed

    private void btnBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookSearchActionPerformed
        searchBook();
    }//GEN-LAST:event_btnBookSearchActionPerformed

    private void btnBookClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookClearFieldsActionPerformed
        clearFields(txtBookId, txtBookTitle, txtBookIsbn, txtBookAuthor, txtBookYear, txtBookCategoria, txtBookEditora);
    }//GEN-LAST:event_btnBookClearFieldsActionPerformed

    private void btnBookRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookRegisterActionPerformed
        registerBook();
        
    }//GEN-LAST:event_btnBookRegisterActionPerformed

    private void addAoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAoPedidoActionPerformed
        addBookAoPedido();
    }//GEN-LAST:event_addAoPedidoActionPerformed

    private void btnConfirmarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCpfActionPerformed
        abrirPedido();
    }//GEN-LAST:event_btnConfirmarCpfActionPerformed

    private void btnCancelarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCpfActionPerformed
        modalSolicitarCpf.dispose();
        clearFields(txtNovoEmprestimoModalCpf);
    }//GEN-LAST:event_btnCancelarCpfActionPerformed

    private void btnNovoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoEmprestimoActionPerformed
        abrirPedido();
    }//GEN-LAST:event_btnNovoEmprestimoActionPerformed

    private void btnSavePedidoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePedidoEmpActionPerformed
        pedidoEmprestimo.processarPedido();
        pedidoEmprestimo = null;
        painelPedido.setVisible(false);
        btnNovoEmprestimo.setVisible(true);
    }//GEN-LAST:event_btnSavePedidoEmpActionPerformed

    private void btnAdicionarAoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAoPedidoActionPerformed
        addBookAoPedido();
    }//GEN-LAST:event_btnAdicionarAoPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
              /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAoPedido;
    private javax.swing.JPanel booksPanel;
    private javax.swing.JButton btnAdicionarAoPedido;
    private javax.swing.JButton btnBookClearFields;
    private javax.swing.JButton btnBookRegister;
    private javax.swing.JButton btnBookSearch;
    private javax.swing.JButton btnBookUpdate;
    private javax.swing.JButton btnCancelarCpf;
    private javax.swing.JButton btnConfirmarCpf;
    private javax.swing.JButton btnNovoEmprestimo;
    private javax.swing.JButton btnSavePedidoEmp;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelBookStatus;
    private javax.swing.JLabel labelNomeLivro;
    private javax.swing.JMenuItem menuDeleteUser;
    private javax.swing.JMenuItem menuEditUser;
    private javax.swing.JDialog modalSolicitarCpf;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JDialog newUserModal;
    private javax.swing.JPanel painelPedido;
    private javax.swing.JPanel painelStatusLivro;
    private javax.swing.JPopupMenu popupBook;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTable tbBooks;
    private javax.swing.JPopupMenu tbOptions;
    private javax.swing.JTable tbPedidoEmprestimo;
    private javax.swing.JTable tbUsers;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookCategoria;
    private javax.swing.JTextField txtBookEditora;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookIsbn;
    private javax.swing.JTextField txtBookSearch;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtBookYear;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCpfPedidoEmprestimo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNovoEmprestimoModalCpf;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
    
    private Usuario getUserTxtFieldData(){
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Usuario usuario = new Usuario();
        usuario.setCpf(txtCpf.getText());
        usuario.setNome(txtNome.getText());
        usuario.setEmail(txtEmail.getText());
        usuario.setTelefone(txtTelefone.getText());
        LocalDate nasc = LocalDate.parse(txtNascimento.getText(), fmt);
        usuario.setDataNasc(nasc);
        usuario.setEndereco(txtEndereco.getText());
        return usuario;
    }
    
    private Livro getBookTxtFieldData(){
        Livro book = new Livro();
        if (txtBookId.getText().matches("^\\d+$")) {
            book.setCodLivro(Integer.parseInt(txtBookId.getText()));
        } else {
            book.setCodLivro(null);
        }
        book.setTitulo(txtBookTitle.getText());
        String[] authors = txtBookAuthor.getText().split(", ");
        List<Autor> listAuthors = new ArrayList<>();
        for (String author : authors) {
            Autor autor = new Autor(null, author);
            listAuthors.add(autor);
        }
        book.setAutor(listAuthors);
        book.setIsbn(txtBookIsbn.getText());
        book.setAnoPub(Integer.parseInt(txtBookYear.getText()));
        Categoria categoria = new Categoria(null, "");
        categoria.setNome(txtBookCategoria.getText());
        book.setCategoria(categoria);
        Editora editora = new Editora(null, "");
        editora.setNome(txtBookEditora.getText());
        book.setEditora(editora);
        return book;
    }
    
    private void clearFields(JTextField ...fields) {
        for (JTextField field : fields) {
            field.setText("");
        }
    }
    
    
    private void registerUser() {
        txtCpf.setEnabled(true);
        Usuario usuario = getUserTxtFieldData();
        biblioteca.registerUsuario(usuario);
        newUserModal.dispose();
        listUsers();
        clearFields(txtCpf, txtEmail, txtEndereco, txtNome, txtNascimento, txtTelefone);
    }
    
    private void editUser() {
        Usuario usuario = getUserTxtFieldData();
        biblioteca.updateUsuario(usuario);
        newUserModal.dispose();
        listUsers();
        clearFields(txtCpf, txtEmail, txtEndereco, txtNome, txtNascimento, txtTelefone);
    }
    
    private void listUsers() {
        populateUserRows(biblioteca.listAllUser());
    }
    
    private void populateUserRows(List<Usuario> list) {
        DefaultTableModel model = (DefaultTableModel) tbUsers.getModel();
        model.setNumRows(0);
        
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                list.get(i).getCpf(),
                list.get(i).getNome(),
                list.get(i).getEmail(),
                list.get(i).getTelefone(),
                list.get(i).getDataNasc().format(DateTimeFormatter.ofPattern("dd/MM/YYYY")),
                list.get(i).getEndereco()
            });
        }
    }
    
    private void populateBookRows(List<Livro> list) {
        DefaultTableModel model = (DefaultTableModel) tbBooks.getModel();
        model.setNumRows(0);
        
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                list.get(i).getCodLivro(),
                list.get(i).getTitulo(),
                list.get(i).getIsbn(),
                list.get(i).getNomesAutores(),
                list.get(i).getAnoPub(),
                list.get(i).getCategoria().getNome(),
                list.get(i).getEditora().getNome()
            });
        }
    }
    
    private void populatePedidoTb(List<Emprestimo> list) {
        DefaultTableModel model = (DefaultTableModel) tbPedidoEmprestimo.getModel();
        model.setNumRows(0);
        
        for (int i = 0; i < list.size(); i++) {
            model.addRow(new Object[]{
                list.get(i).getLivro().getCodLivro(),
                list.get(i).getLivro().getTitulo()  
            });
        }
    }
    
    private void showEditModal() {
        int selected = tbUsers.getSelectedRow();
        txtCpf.setText(tbUsers.getModel().getValueAt(selected, 0).toString());
        txtNome.setText(tbUsers.getModel().getValueAt(selected, 1).toString());
        txtEmail.setText(tbUsers.getModel().getValueAt(selected, 2).toString());
        txtTelefone.setText(tbUsers.getModel().getValueAt(selected, 3).toString());
        txtNascimento.setText(tbUsers.getModel().getValueAt(selected, 4).toString());
        txtEndereco.setText(tbUsers.getModel().getValueAt(selected, 5).toString());
        txtCpf.setEnabled(false);
        registerBtn.setVisible(false);
        editBtn.setVisible(true);
        newUserModal.setVisible(true);
    }
    
    private void searchUser() {
        String txt = txtSearch.getText();
        populateUserRows(biblioteca.searchUser(txt));
    }
    
    private void searchBook() {
        String txt = txtBookSearch.getText();
        populateBookRows(biblioteca.searchBook(txt));
    }
    
    private void deleteUser() {
        int selected = tbUsers.getSelectedRow();
        String cpf = tbUsers.getModel().getValueAt(selected, 0).toString();
        biblioteca.deleteUser(cpf);
        listUsers();
    }
    
    private void registerBook() {
        Livro livro = getBookTxtFieldData();
        biblioteca.registerLivro(livro);
        clearFields(txtBookId, txtBookTitle, txtBookIsbn, txtBookAuthor, txtBookYear, txtBookCategoria, txtBookEditora);
    }
    
    private void addBookAoPedido() {
        int selected = tbBooks.getSelectedRow();
        if (selected != -1) {
            if (pedidoEmprestimo == null) {
                novoEmprestimo();
            } else {
                int idLivro = Integer.valueOf(tbBooks.getModel().getValueAt(selected, 0).toString());
                Livro livro = biblioteca.findBookById(idLivro);
                pedidoEmprestimo.addBook(livro);
                populatePedidoTb(pedidoEmprestimo.getEmprestimos());
            }
        }
    }
    
    private void novoEmprestimo() {
        modalSolicitarCpf.setVisible(true);
    }
    
    private void abrirPedido() {
        String cpf = txtNovoEmprestimoModalCpf.getText();
        Usuario usuario = biblioteca.searchUserByCpf(cpf);
        if (usuario != null) {
            pedidoEmprestimo = new PedidoEmprestimo(usuario.getCpf());
            modalSolicitarCpf.dispose();
            clearFields(txtNovoEmprestimoModalCpf);
        }
        btnNovoEmprestimo.setVisible(false);
        txtCpfPedidoEmprestimo.setText(usuario.getCpf());
        painelPedido.setVisible(true);
        addBookAoPedido();
        
    }
    
    ListSelectionListener listListener = new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) { 
                int selectedRow = tbBooks.getSelectedRow();
                if (selectedRow != -1) {
                    painelStatusLivro.setVisible(true);
                    int idLivro = Integer.parseInt(tbBooks.getModel().getValueAt(selectedRow, 0).toString());
                    labelNomeLivro.setText(tbBooks.getModel().getValueAt(selectedRow, 1).toString());
                    List<Emprestimo> list = biblioteca.obterEmprestimosAssociadosAUmLivro(idLivro);
                    if (list.size() > 0) {
                        labelBookStatus.setText("Indisponível");
                        btnAdicionarAoPedido.setVisible(false);
                    } else {
                        labelBookStatus.setText("Disponível");
                        btnAdicionarAoPedido.setVisible(true);  
                    }
                }
            } 
        }
    };
}
